#ifndef _APPLICATIONUSBWATCHER_H
#define _APPLICATIONUSBWATCHER_H
/*****************************************************/
/* ApplicationUsbWatcher based on BApplication class */
/* Created : 24/2/2003 - 18:6:8                      */
/* Code Generated by MeTOS                           */
/*****************************************************/

#include <Application.h>

class WindowMain;

class ApplicationUsbWatcher : public BApplication
{
public:
	// public functions
	ApplicationUsbWatcher(const char *signature);
	virtual	void 	ReadyToRun();
	virtual void	MessageReceived(BMessage* message);
	virtual void 	AppActivated(bool active);
	int				dev;
protected:
	// protected members
	WindowMain		*_windowmain;

};

#endif